### ISSUE TITLE
Input file is not updated with nested JSON key

### ISSUE THREAD

**Issue by askrinnik** [iamazeem/substitute-action#1]
Hi,
Thank you for your action. 
I wanted to use it instead of deprecated  **microsoft/variable-substitution** 

Here is my original workflow step:
```
    - name: Setting Connection String  
      uses: microsoft/variable-substitution@v1
      with: 
       files: '${{ github.workspace }}/Edge.Web/appsettings.json'
      env: 
       EdgeSecrets.Databases.NetMeter.ConnectionString: ${{ secrets.PERFORMANCE_TESTS_DB_CONNECTION_STRING }}

```
I replaced it with your action:
```
    - name: Setting Connection String  
      uses: iamazeem/substitute-action@v1
      with: 
       input-files: '${{ github.workspace }}/Edge.Web/appsettings.json'
      env: 
       EdgeSecrets.Databases.NetMeter.ConnectionString: ${{ secrets.PERFORMANCE_TESTS_DB_CONNECTION_STRING }}

```
in fact, I just changed **files** to **input-files**
Unfortunately, the input **appsettings.json** was not updated after action processing

The workflow is executed on the self-hosted server with Windows Server 2019

**Additional context**
Here is the action execution log:
![image](https://github.com/iamazeem/substitute-action/assets/1359187/2e5f423d-45bd-483c-9f87-428ba6780624)

Could you help me to understand the root cause of the issue?
Thank you in advance

**Comment by iamazeem** [comment]
Hi @askrinnik,

Thank you for creating this issue!

Actually, this action is not a drop-in replacement for https://github.com/microsoft/variable-substitution.
It performs substitution on any type of file, be it a JSON, YAML, or a simple plain text file i.e. it's file format agnostic.

As mentioned in the [README](https://github.com/iamazeem/substitute-action#features), it works with Bash/shell variable syntax i.e. `$VAR` or `${VAR}`.
Each instance of `$VAR` or `${VAR}` will be substituted in the `input-files` by its respective value (if available).
Only underscores are allowed in the variable names as other characters make a shell variable name invalid.
The validation stage does report on such issues.

So, for this sample `appsettings.json`:

```json
{
    "EdgeSecrets.Databases.NetMeter.ConnectionString": "${PERFORMANCE_TESTS_DB_CONNECTION_STRING}"
}
```

or,

```json
{
  "EdgeSecrets": {
    "Databases": {
      "NetMeter": {
        "ConnectionString": "${PERFORMANCE_TESTS_DB_CONNECTION_STRING}"
      }
    }
  }
}
```

The following workflow step should perform the substitution:

```yml
    - name: Setting Connection String  
      uses: microsoft/variable-substitution@v1
      env:
        PERFORMANCE_TESTS_DB_CONNECTION_STRING: ${{ secrets.PERFORMANCE_TESTS_DB_CONNECTION_STRING }}
      with:
        inputs-files: '${{ github.workspace }}/Edge.Web/appsettings.json'
```

Let me know if this works fine for your use case.

---

Apart from that, for format specific files such as JSON and YAML, you may simply use [jq](https://github.com/jqlang/jq) and [yq](https://github.com/mikefarah/yq) respectively.
